Разметка главной страницы
htmlacademy-adaptive/870593-pink-21 pull request #2
Opened 2020-11-13 13:29 UTC by Pshesh

2020-11-13 15:57 UTC, lipa88-mk requested changes
Добавила несколько комментариев, если что-то непонятно или есть вопросы, то их можно задать прямо под комментарием в самом пуллреквесте :)

2020-11-13 15:57 UTC, lipa88-mk commented on source/index.html
> +            </li>
Опечатка в названии класса - socail вместо social :)

2020-11-13 15:57 UTC, lipa88-mk commented on source/index.html
> +          <thead class="table-head">
table-head - это вряд ли отдельный блок, так как без тега тэйбл мы не можем где-то в коде написать просто thead, так что это тоже элемент. Но это элемент таблицы, не секции. Так что тут можно было бы смиксовать. Таблица одновременно является блоком секции section class="price", и при этом она тоже является блоком, внутри которого есть все элементы таблицы. Так что тут нужно вроде: 
 table class="price__table table" и далее thead class="table__head", th class="table__value table__value--empty" и так далее

2020-11-13 15:57 UTC, lipa88-mk commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
Вот тут получается немного странно, что это элементы разных блоков. Лучше оставить что-то одно

2020-11-13 15:57 UTC, lipa88-mk commented on source/index.html
> +                  <img src="https://via.placeholder.com/150x150" alt="Logo Microsoft Store">
Вот тут у картинок есть альт - это совершенно верно, но не у всех картинок на странице он есть. Желательно сразу же на этом этапе добавить, так как этот момент есть в критериях и ТЗ и лучше сразу его проконтролировать

2020-11-13 15:57 UTC, lipa88-mk commented on source/index.html
> +    <nav class="main-nav">
main-nav еще и элемент шапки, так что тут нужен еще и класс вроде page-header__nav

2020-11-13 15:57 UTC, lipa88-mk commented on source/index.html
> +            <a href="">
Так как мы уже на главной, то href можно вообще не писать. А в других пунктах в дальнейшем нужно будет добавить ссылки на будущие страницы каталога и формы. Но это потом

2020-11-13 18:24 UTC, Pshesh commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
Медленно въезжаю в тему БЭМа и миксования)

Делала это по примеру Барбершопа
  <section class="reviews">
    <div class="reviews__wrapper slider">
      <h2 class="reviews__title">Отзывы о нас</h2>
      <div class="reviews__list slider__list">
        <blockquote class="reviews__item slider__item">
          <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Трэвиса Баркера">
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Трэвис Баркер</cite>
            <p class="reviews__text">Спасибо за лысину! Был проездом в Москве, заскочил побриться, чтобы было видно новую татуировку!</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Джона Смита">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Джон Смит</cite>
            <p class="reviews__text">Отличную стрижку мне сделали ребята.</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Ивана Бородайло">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Иван Бородайло</cite>
            <p class="reviews__text">В Бородинском ваша борода в надёжных руках!</p>
          </div>
        </blockquote>
      </div>
      <p class="reviews__toggles slider__toggles">
        <button class="slider__toggle slider__toggle--current" type="button">1</button>
        <button class="slider__toggle" type="button">2</button>
        <button class="slider__toggle" type="button">3</button>
      </p>
    </div>
  </section>

2020-11-13 18:29 UTC, Pshesh commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
Медленно въезжаю в тему БЭМа и миксования.
Делала это по примеру Барбершопа. Может что то не так поняла или где то ошиблась.
`  <section class="reviews">
    <div class="reviews__wrapper slider">
      <h2 class="reviews__title">Отзывы о нас</h2>
      <div class="reviews__list slider__list">
        <blockquote class="reviews__item slider__item">
          <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Трэвиса Баркера">
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Трэвис Баркер</cite>
            <p class="reviews__text">Спасибо за лысину! Был проездом в Москве, заскочил побриться, чтобы было видно новую татуировку!</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Джона Смита">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Джон Смит</cite>
            <p class="reviews__text">Отличную стрижку мне сделали ребята.</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Ивана Бородайло">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Иван Бородайло</cite>
            <p class="reviews__text">В Бородинском ваша борода в надёжных руках!</p>
          </div>
        </blockquote>
      </div>
      <p class="reviews__toggles slider__toggles">
        <button class="slider__toggle slider__toggle--current" type="button">1</button>
        <button class="slider__toggle" type="button">2</button>
        <button class="slider__toggle" type="button">3</button>
      </p>
    </div>
  </section>`

2020-11-13 18:30 UTC, Pshesh commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
Не пойму правильно ли я вставляю этот кусочек кода. 
Это разметка главной старницы барбершопа с отзывами

2020-11-13 18:32 UTC, Pshesh commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
`  <section class="reviews">
    <div class="reviews__wrapper slider">
      <h2 class="reviews__title">Отзывы о нас</h2>
      <div class="reviews__list slider__list">
        <blockquote class="reviews__item slider__item">
          <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Трэвиса Баркера">
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Трэвис Баркер</cite>
            <p class="reviews__text">Спасибо за лысину! Был проездом в Москве, заскочил побриться, чтобы было видно новую татуировку!</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Джона Смита">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Джон Смит</cite>
            <p class="reviews__text">Отличную стрижку мне сделали ребята.</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Ивана Бородайло">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Иван Бородайло</cite>
            <p class="reviews__text">В Бородинском ваша борода в надёжных руках!</p>
          </div>
        </blockquote>
      </div>
      <p class="reviews__toggles slider__toggles">
        <button class="slider__toggle slider__toggle--current" type="button">1</button>
        <button class="slider__toggle" type="button">2</button>
        <button class="slider__toggle" type="button">3</button>
      </p>
    </div>
  </section>
`

2020-11-13 18:33 UTC, Pshesh commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
`  <section class="reviews">
    <div class="reviews__wrapper slider">
      <h2 class="reviews__title">Отзывы о нас</h2>
      <div class="reviews__list slider__list">
        <blockquote class="reviews__item slider__item">
          <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Трэвиса Баркера">
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Трэвис Баркер</cite>
            <p class="reviews__text">Спасибо за лысину! Был проездом в Москве, заскочил побриться, чтобы было видно новую татуировку!</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Джона Смита">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Джон Смит</cite>
            <p class="reviews__text">Отличную стрижку мне сделали ребята.</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Ивана Бородайло">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Иван Бородайло</cite>
            <p class="reviews__text">В Бородинском ваша борода в надёжных руках!</p>
          </div>
        </blockquote>
      </div>
      <p class="reviews__toggles slider__toggles">
        <button class="slider__toggle slider__toggle--current" type="button">1</button>
        <button class="slider__toggle" type="button">2</button>
        <button class="slider__toggle" type="button">3</button>
      </p>
    </div>
  </section>`

2020-11-13 18:53 UTC, Pshesh commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
```
 <section class="reviews">
    <div class="reviews__wrapper slider">
      <h2 class="reviews__title">Отзывы о нас</h2>
      <div class="reviews__list slider__list">
        <blockquote class="reviews__item slider__item">
          <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Трэвиса Баркера">
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Трэвис Баркер</cite>
            <p class="reviews__text">Спасибо за лысину! Был проездом в Москве, заскочил побриться, чтобы было видно новую татуировку!</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Джона Смита">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Джон Смит</cite>
            <p class="reviews__text">Отличную стрижку мне сделали ребята.</p>
          </div>
        </blockquote>
        <blockquote class="reviews__item slider__item">
          <picture class="reviews__author-picture">
            <source media="(min-width: 1200px)" srcset="img/picture-travis-desktop@1x.jpg 1x">
            <source media="(min-width: 768px)" srcset="img/picture-travis-tablet@1x.jpg 1x">
            <img class="reviews__author-image" src="img/picture-travis-mobile@1x.jpg" width="50" height="33" alt="Фото Ивана Бородайло">
          </picture>
          <div class="reviews__author-info">
            <cite class="reviews__author-name">Иван Бородайло</cite>
            <p class="reviews__text">В Бородинском ваша борода в надёжных руках!</p>
          </div>
        </blockquote>
      </div>
      <p class="reviews__toggles slider__toggles">
        <button class="slider__toggle slider__toggle--current" type="button">1</button>
        <button class="slider__toggle" type="button">2</button>
        <button class="slider__toggle" type="button">3</button>
      </p>
    </div>
  </section>
```

2020-11-13 19:13 UTC, lipa88-mk commented on source/index.html
> +          <blockquote class="reviews__item slider__item">
Хм... Неожиданно) Тогда вопрос снят)

2020-11-14 11:15 UTC, lipa88-mk commented
Всё хорошо)

2020-11-14 11:15 UTC, merged