Разметка страницы формы
htmlacademy-adaptive/870593-pink-21 pull request #3
Opened 2020-11-15 15:22 UTC by Pshesh

2020-11-15 20:45 UTC, lipa88-mk requested changes
Во многих тегах не хватает второго класса для блока. То есть ниже идут классы для элементов блока, значит выше нужен класс блока, так как элементы не могут быть вне своего блока. Можно проверять себя вот этим сервисом: https://yoksel.github.io/html-tree/ Помогает найти неточности)

2020-11-15 20:45 UTC, lipa88-mk commented on source/form.html
> +    <nav class="page-header__nav">
Нужно добавить еще класс блока nav, так как ниже идут его элементы)

2020-11-15 20:45 UTC, lipa88-mk commented on source/form.html
> +    <section class="page-main__intro">
А тут добавить класс блока интро, элементы которого идут ниже. Элементы не могут быть без блока)

2020-11-15 20:45 UTC, lipa88-mk commented on source/form.html
> +          <fieldset class="contest-form__user-info">
Тут добавить класс блока user-info

2020-11-15 20:45 UTC, lipa88-mk commented on source/form.html
> +            <fieldset class="contest-form__user-achieves">
А тут нужен блок user-achieves :)

2020-11-15 20:45 UTC, lipa88-mk commented on source/form.html
> +                      name="Сделал селфи с акулой" checked>
В атрибуте name нужно задать имя переменной, которая будет хранить значение, введенное в поле. Поэтому тут нельзя использовать русские буквы, можно только латиницу. Подбор слова по принципу именования классов получается) Можно что-то типа shark, chack, souvenirs  и так далее. Нужно поправить во всех инпутах, либо name можно вообще убрать

2020-11-15 20:45 UTC, lipa88-mk commented on source/form.html
> +          <fieldset class="contest-form__user-opinion">
Тут тоже не хватает второго класса для элементов блока, что идут  ниже

2020-11-16 07:53 UTC, Pshesh commented on source/form.html
> +    <section class="page-main__intro">
Все, я поняла) Спасибо за ссылку!)

2020-11-16 10:30 UTC, merged