Стилизация главной страницы
htmlacademy-adaptive/870593-pink-21 pull request #5
Opened 2020-11-20 22:01 UTC by Pshesh

У меня почему то по размерам и отступам как будто внешне расходится с макетом в некоторых местах. Я не понимаю почему, вроде все указываю как там.

2020-11-21 20:56 UTC, lipa88-mk requested changes
Немного перестаралась)) Предлагаю сейчас закомментировать часть с шириной страницы и убрать пока width: 320px;    min-height: 100%;    margin: 0 auto; у body, это будет позднее на этипе сеток. Пусть пока текст будет растягиваться от края до края  страницы и выровнен налево или по центру. Нужно немного поправить вложенности во всех блоках, на одном из расписала подробнее ниже. И еще немного проверить параметры текста. Есть подвох в цветах - темно синий  и черный в макете очень похожи и местами цвет не тот. И жирность текста тоже иногда не совпадает, лучше еще раз просмотреть. В этом помогает вкладка Computed в просмотре кода. Там же самой последней строчкой есть название шрифта, которым в итоге был написан текст и можно проверить, подгрузился ли наш шрифт или нет.

2020-11-21 20:56 UTC, lipa88-mk commented on source/sass/blocks/contacts.scss
> +
Вложенность сделана не совсем верно. Тут нужно либо использовать название с амперсандом:
.contacts {
   &__wrapper {   ...  }
   &__header {...}
}

Либо если писать селектор без амперсанда, то не вкладывать внутрь фигурных скобок родителя.
Так как при написании кода как есть сейчас в результате получаются более специфичные правила со вложенностью вида 
.contacts  .contacts__wrapper {...}
.contacts  .contacts__header  {...}
что противоречит подхожу БЭМ и критерию Д10 Вложенность селекторов не больше двух уровней. Так что я бы тогда писала бы в аналогичных ситуациях без вложенности, просто отдельные правила как в обычном css)

2020-11-21 20:56 UTC, lipa88-mk commented on source/sass/blocks/copyright.scss
> +  }
вложенность 3х уровней(

2020-11-21 20:56 UTC, lipa88-mk commented on source/sass/blocks/features.scss
> +    background-image: url("../../img/grey\ background.png");
Относительные пути должны быть указаны относительно файла style.css, ведь именно его мы подключаем к странице. Не относительно препроцессорного файла. Иначе фон не находится.
Это можно проверять в опубликованной версии, как только был отправлен ПР: https://htmlacademy-adaptive.github.io/870593-pink-21/5/
Тут как раз видно, что фоны не загрузились как раз по этой причине

2020-11-21 20:56 UTC, lipa88-mk commented on source/sass/blocks/page.scss
> +  }
А вот такая вложенность допускается)

2020-11-21 20:56 UTC, lipa88-mk commented on source/sass/blocks/page.scss
> +  }
А вот это лучше вынести в отдельное правило

2020-11-21 20:56 UTC, lipa88-mk commented on source/sass/blocks/price.scss
> +  background: url("../../img/price\ grey\ background.png");
С адресом что-то не так)) Слеши и пробелы

2020-11-21 20:56 UTC, lipa88-mk commented on source/index.html
> +          <small class="intro__info">
Написание шрифта не по макету, жирность 300, размер шрифта 14пх

2020-11-21 20:56 UTC, lipa88-mk commented on source/index.html
> +              <p class="features__description">
Weight  - 400

2020-11-21 20:56 UTC, lipa88-mk commented on source/index.html
>                <cite class="reviews__author-name">
Цвет черный)

2020-11-21 20:56 UTC, lipa88-mk commented on source/index.html
> +        <table class="price__table table">
Давай пока без надписи ХИТ) Пусть пока будет таблица с отступами, нужно еще раз в ней проверить цвета и написания текста. Сначала должна быть сделана глобальная сетка, потом уже декоративные элементы. Можно пока эту часть закомментировать, чтобы вернуться к ней позднее

2020-11-22 15:48 UTC, Pshesh commented on source/sass/blocks/page.scss
> +  }
Не очень поняла по поводу отдельного правила. Параметры шрифта?

2020-11-22 16:59 UTC, Pshesh commented on source/sass/blocks/page.scss
> +  }
Все, кажись поняла)

2020-11-22 18:27 UTC, Pshesh commented on source/sass/blocks/button.scss
> +}
Кнопка по размерам получается больше, чем в макете.

2020-11-22 20:30 UTC, lipa88-mk commented on source/sass/blocks/page.scss
> +  }
Я имела в виду, что не использовать вложенность {} в {} :)

2020-11-22 20:38 UTC, lipa88-mk commented on source/sass/blocks/button.scss
> +}
По ширине ее можно ограничить позднее, либо сейчас задав ширину. И лучше паддинги во все стороны сделать, так как текста может быть в кнопке любое количество и он не должн оказаться у самого края кнопки. И по высоте можно немного уменьшить паддинг, чтобы высота совпала с макетом

2020-11-22 20:49 UTC, lipa88-mk requested changes
Еще немного правок, если есть вопросы - пиши сюда или в Телеграмм)

2020-11-22 20:49 UTC, lipa88-mk commented on source/sass/blocks/page-body.scss
> +.page-body {
в разметке он же теперь page__body, нужно поправить в разметке обратно

2020-11-22 20:49 UTC, lipa88-mk commented on source/sass/blocks/page-body.scss
> +.page-body {
А то шрифт на всей странице стал Таймс Нью Роман

2020-11-22 20:49 UTC, lipa88-mk commented on source/sass/blocks/page-body.scss
> +.page-body {
page-body - это блок, поэтому он в своем файле, тут все верно. Как с page-header, например

2020-11-23 06:28 UTC, Pshesh commented on source/sass/blocks/page-body.scss
> +.page-body {
Привет!
А я в разметке .page__body перемеиновала на .page-body, потому что в генераторе дерева мне все время подчеркивало его. Так не правильно, обратно переиминовать в разметке на .page__body?

2020-11-23 12:00 UTC, merged